[project]
name = "stacks-mfers"

[contracts.stacks-mfers]
depends_on = ["nft-trait", "commission-trait"]
path = "contracts/stacks-mfers.clar"

[contracts.stacks-mfers-stacks-art-commission]
depends_on = ["commission-trait"]
path = "contracts/stacks-mfers-stacks-art-commission.clar"

[contracts.commission-trait]
depends_on = []
path = "contracts/commission-trait.clar"

[contracts.nft-trait]
depends_on = []
path = "contracts/nft-trait.clar"
