[project]
name = "stacks-mfers"

[contracts.stacks-mfers]
depends_on = ["nft-trait", "commission-trait"]
path = "contracts/stacks-mfers.clar"

[contracts.stacks-mfers-stacks-art-commission]
depends_on = ["commission-trait"]
path = "contracts/stacks-mfers-stacks-art-commission.clar"

[contracts.mfer-token]
depends_on = ["ft-trait"]
path = "contracts/mfer-token.clar"

[contracts.usdm-token]
depends_on = ["ft-trait"]
path = "contracts/usdm-token.clar"

[contracts.usdm-minter]
depends_on = ["usdm-token"]
path = "contracts/usdm-minter.clar"

##########
# Traits #
##########
[contracts.commission-trait]
depends_on = []
path = "contracts/commission-trait.clar"

[contracts.nft-trait]
depends_on = []
path = "contracts/nft-trait.clar"

[contracts.ft-trait]
depends_on = []
path = "contracts/ft-trait.clar"
